
server:
  address: localhost
  port: 8080

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/example?serverTimezone=UTC&characterEncoding=UTF-8
    username : root
    password: 1234
    driver-class-name : com.mysql.cj.jdbc.Driver